import { useLocation } from "wouter";

const routeToTabMap: Record<string, string> = {
  "/admin": "overview",
  "/admin/monitoring": "monitoring",
  "/admin/health-alerts": "health-alerts",
  "/admin/launch-readiness": "launch-readiness",
  "/admin/ops-readiness": "ops-readiness",
  "/admin/drivers": "drivers",
  "/admin/riders": "riders",
  "/admin/directors": "directors",
  "/admin/my-drivers": "my-drivers",
  "/admin/admin-management": "admin-management",
  "/admin/role-appointments": "role-appointments",
  "/admin/training": "training",
  "/admin/training-center": "training-center",
  "/admin/rider-trust": "rider-trust",
  "/admin/pairing-blocks": "pairing-blocks",
  "/admin/trips": "trips",
  "/admin/reservations": "reservations",
  "/admin/ride-classes": "ride-classes",
  "/admin/driver-prefs": "driver-prefs",
  "/admin/corporate": "corporate",
  "/admin/special-rides": "special-rides",
  "/admin/simulation": "simulation",
  "/admin/fee-settings": "fee-settings",
  "/admin/payouts": "payouts",
  "/admin/wallets": "wallets",
  "/admin/wallet-funding": "wallet-funding",
  "/admin/director-funding": "director-funding",
  "/admin/third-party-funding": "third-party-funding",
  "/admin/refunds": "refunds",
  "/admin/chargebacks": "chargebacks",
  "/admin/bank-transfers": "bank-transfers",
  "/admin/cash-settlements": "cash-settlements",
  "/admin/cash-disputes": "cash-disputes",
  "/admin/tax-documents": "tax-documents",
  "/admin/ratings": "ratings",
  "/admin/disputes": "disputes",
  "/admin/inbox": "inbox",
  "/admin/help-center": "help-center",
  "/admin/support-logs": "support-logs",
  "/admin/fraud": "fraud",
  "/admin/safety": "safety",
  "/admin/lost-items": "lost-items",
  "/admin/lost-item-fraud": "lost-item-fraud",
  "/admin/accident-reports": "accident-reports",
  "/admin/insurance": "insurance",
  "/admin/relief-fund": "relief-fund",
  "/admin/compliance-logs": "compliance-logs",
  "/admin/store-compliance": "store-compliance",
  "/admin/reports": "reports",
  "/admin/growth": "growth",
  "/admin/user-growth": "user-growth",
  "/admin/incentives": "incentives",
  "/admin/acquisition": "acquisition",
  "/admin/countries": "countries",
  "/admin/contracts": "contracts",
  "/admin/overrides": "overrides",
  "/admin/zibra-insights": "zibra-insights",
  "/admin/welcome-insights": "welcome-insights",
  "/admin/zibra-governance": "zibra-governance",
  "/admin/director-settings": "director-settings",
  "/admin/director-performance": "director-performance",
};

export function useActiveTabFromRoute(): string {
  const [location] = useLocation();
  return routeToTabMap[location] || "overview";
}

export { routeToTabMap };
